name: CD - Limosia Backend

on:
  pull_request:
    branches: ['development']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Make sure node is installed first
      - uses: actions/checkout@v2
      - name: Setup Nodejs and NPM
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      # Then we're installing yarn and pm2
      - name: Setup yarn
        run: npm install -g yarn

      - name: Installing PM2
        run: npm install -g pm2

      - name: Setup Nodejs with yarn caching
        uses: actions/setup-node@v2
        with:
          node-version: '18'
          cache: yarn

      - name: Auto Deploy using SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          # key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          script: |
            cd ~/apps/limosia-backend
            git fetch --all
            git checkout development
            git pull
            git status
            yarn install --frozen-lockfile
            yarn build
            pm2 restart LimosiaBackend

      # Uninstall when we're done
      - name: Clean up
        if: always()
        run: npm uninstall -g yarn pm2
