name: CD

on:
  push:
    branches: ['development']

jobs:
  deploy:
    - name: Deploy to Server
      runs-on: ubuntu-latest

      steps:
        - name: Deploy using SSH
          uses: appleboy/ssh-action@v1.0.0
          with:
            host: ${{ secrets.HOST }}
            username: ${{ secrets.USERNAME }}
            key: ${{ secrets.PRIVATE_KEY }}
            port: 22
            script: |
              whoami
              export NVM_DIR=~/.nvm
              source ~/.nvm/nvm.sh

              cd ~/apps/limosia-backend
              git fetch --all
              git checkout development
              git pull
              git status

              yarn install --frozen-lockfile
              yarn migration:run
              yarn build

              pm2 restart LimosiaBackend
