name: CI

on:
  pull_request:
    branches: ['main', 'development']

jobs:
  test:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-nodejs

      - name: Run Test
        run: yarn test

  test_dist:
    name: Test Dist
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-nodejs

      - name: Production Dist Test
        run: yarn build

  linting:
    name: Linting
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-nodejs

      - name: ESLint
        run: yarn lint
